accessing
isException: anObject
	isException := anObject