accessing
exception
	<return: #Exception or: nil>
	^ exception